### ISSUE TITLE
no main manifest attribute, in efactuur2pdf-3.0.0.jar

### ISSUE THREAD

**Issue by MircoBabin** [eluinstra/efactuur2pdf#1]
The command:

```java -jar efactuur2pdf-3.0.0.jar nl.ordina.digikoppeling.ebf.ValidateFile "c:\users\mirco\Documents\Factuur_2170249.xml"```

Resulted in the error:

```no main manifest attribute, in efactuur2pdf-3.0.0.jar```

OS:
Microsoft Windows/11

```
java -version

java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
Java HotSpot(TM) Client VM (build 25.361-b09, mixed mode, sharing)
```

**Comment by MircoBabin** [comment]
When using -cp:

```java -cp efactuur2pdf-3.0.0.jar nl.ordina.digikoppeling.ebf.ValidateFile "c:\users\mirco\Documents\Factuur_2170249.xml"```

Is also doesn't work and produces:

```
Exception in thread "main" java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
        at sun.security.util.SignatureFileVerifier.processImpl(Unknown Source)
        at sun.security.util.SignatureFileVerifier.process(Unknown Source)
        at java.util.jar.JarVerifier.processEntry(Unknown Source)
        at java.util.jar.JarVerifier.update(Unknown Source)
        at java.util.jar.JarFile.initializeVerifier(Unknown Source)
        at java.util.jar.JarFile.ensureInitialization(Unknown Source)
        at java.util.jar.JavaUtilJarAccessImpl.ensureInitialization(Unknown Source)
        at sun.misc.URLClassPath$JarLoader$2.getManifest(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```
